[package]
name = "databend-common-exception"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
databend-common-arrow = { path = "../arrow" }

# GitHub dependencies
# TODO: Use the version from crates.io once
# https://github.com/brendanzab/codespan/pull/331 is released.
codespan-reporting = { git = "https://github.com/brendanzab/codespan", rev = "c84116f5" }

anyhow = { workspace = true }
arrow-schema = { workspace = true }
backtrace = { git = "https://github.com/rust-lang/backtrace-rs.git", rev = "6145fe6bac65c38375f1216a565a6cc7deb89a2d" }
#backtrace = "0.3.69"
bincode = { workspace = true }
geos = { workspace = true }
geozero = { workspace = true }
http = "0.2"
opendal = { workspace = true }
parquet = { workspace = true }
paste = "1.0.9"
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tantivy = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["geos"]
