[package]
name = "databend-common-ast"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

# We need to add `geos = { workspace = true }` to enable the feature `static` to pass compilation.
# This line and `geos = { workspace = true }` in the following lines can be removed if crate `geozero` is fixed and updated.
[package.metadata.cargo-machete]
ignored = ["geos"]

[dependencies] # In alphabetical order
# Workspace dependencies
databend-common-base = { path = "../../common/base" }
databend-common-exception = { path = "../../common/exception" }
databend-common-io = { path = "../../common/io" }
databend-common-meta-app = { path = "../../meta/app" }

# Crates.io dependencies
derive-visitor = { workspace = true }
enum-as-inner = "0.5.1"
ethnum = { workspace = true }
fast-float = "0.2.0"
geos = { workspace = true }
indent = "0.1.1"
itertools = { workspace = true }
logos = "0.12.1"
minitrace = { workspace = true }
nom = "7.1.1"
nom-rule = "0.3.0"
ordered-float = { workspace = true }
pratt = "0.4.0"
pretty = "0.11.3"
serde_json = { workspace = true }
strsim = "0.10"
strum = "0.24"
strum_macros = "0.24"
unindent = "0.2.3"
url = "2.3.1"
log = { workspace = true }

[dev-dependencies]
criterion = "0.4"
databend-common-base = { path = "../../common/base" }
goldenfile = "1.4"
pretty_assertions = "1.3.0"
regex = { workspace = true }

[[bench]]
name = "bench"
harness = false
