[package]
name = "databend-storages-common-index"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[package.metadata.cargo-machete]
ignored = ["xorfilter-rs", "match-template"]

[dependencies]
databend-common-arrow = { path = "../../../../common/arrow" }
databend-common-exception = { path = "../../../../common/exception" }
databend-common-expression = { path = "../../../expression" }
databend-common-functions = { path = "../../../functions" }

databend-storages-common-table-meta = { path = "../table_meta" }

anyerror = { workspace = true }
cbordata = { version = "0.6.0" }
crc32fast = "1.3.2"
log = { workspace = true }
match-template = { workspace = true }
minitrace = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tantivy = { workspace = true }
tantivy-common = "0.7.0"
thiserror = { workspace = true }

xorfilter-rs = { git = "https://github.com/datafuse-extras/xorfilter", features = [
    "cbordata",
], tag = "databend-alpha.4" }

parquet = { workspace = true }

[dev-dependencies]
criterion = "0.4"
databend-common-arrow = { path = "../../../../common/arrow" }
rand = { workspace = true }

[[bench]]
name = "build_from_block"
harness = false
