[package]
name = "databend-common-pipeline-sources"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[package.metadata.cargo-machete]
ignored = ["xml-rs"]

[dependencies]
async-backtrace = { workspace = true }
async-channel = "1.7.1"
databend-common-arrow = { path = "../../../common/arrow" }
databend-common-base = { path = "../../../common/base" }
databend-common-catalog = { path = "../../catalog" }
databend-common-compress = { path = "../../../common/compress" }
databend-common-exception = { path = "../../../common/exception" }
databend-common-expression = { path = "../../expression" }
databend-common-formats = { path = "../../formats" }
databend-common-io = { path = "../../../common/io" }
databend-common-meta-app = { path = "../../../meta/app" }
databend-common-pipeline-core = { path = "../core" }
databend-common-settings = { path = "../../settings" }
databend-common-storage = { path = "../../../common/storage" }

async-trait = { workspace = true }
bstr = "1.0.1"
csv-core = "0.1.10"
dashmap = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }

log = { workspace = true }
minitrace = { workspace = true }
opendal = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

typetag = { workspace = true }
xml-rs = "0.8.14"
