[package]
name = "databend-common-meta-app"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
storage-hdfs = []

[dependencies]
databend-common-exception = { path = "../../common/exception" }
databend-common-expression = { path = "../../query/expression" }
databend-common-io = { path = "../../common/io" }
databend-common-meta-kvapi = { path = "../kvapi" }
databend-common-meta-types = { path = "../types" }

anyerror = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
cron = "0.12.0"
enumflags2 = { workspace = true }
hex = "0.4.3"
itertools = { workspace = true }
maplit = "1.0.2"
num-derive = "0.3.3"
num-traits = "0.2.15"
opendal = { workspace = true }
paste = "1.0.9"
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = "0.10.5"
sha2 = "0.10.6"
thiserror = { workspace = true }
log = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["num-traits"]

[build-dependencies]
databend-common-building = { path = "../../common/building" }

tonic-build = { workspace = true }
