[package]
name = "databend-common-catalog"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
databend-common-arrow = { path = "../../common/arrow" }
databend-common-base = { path = "../../common/base" }
databend-common-config = { path = "../config" }
databend-common-exception = { path = "../../common/exception" }
databend-common-expression = { path = "../expression" }
databend-common-io = { path = "../../common/io" }
databend-common-meta-api = { path = "../../meta/api" }
databend-common-meta-app = { path = "../../meta/app" }
databend-common-meta-store = { path = "../../meta/store" }
databend-common-meta-types = { path = "../../meta/types" }
databend-common-pipeline-core = { path = "../pipeline/core" }
databend-common-settings = { path = "../settings" }
databend-common-storage = { path = "../../common/storage" }
databend-common-users = { path = "../users" }
databend-storages-common-table-meta = { path = "../storages/common/table_meta" }
databend-storages-common-txn = { path = "../storages/common/txn" }

arrow-schema = { workspace = true }
async-backtrace = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
dashmap = { workspace = true }
dyn-clone = "1.0.9"
log = { workspace = true }
parking_lot = { workspace = true }
parquet_rs = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10.6"
thrift = "0.17.0"
typetag = { workspace = true }
xorf = { version = "0.11.0", default-features = false, features = ["binary-fuse"] }

[dev-dependencies]
goldenfile = "1.4"
