[package]
name = "databend-common-io"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
databend-common-exception = { path = "../exception" }

# Crates.io dependencies
bincode = { workspace = true }
borsh = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
ethnum = { workspace = true }
geo = { workspace = true }
geos = { workspace = true }
geozero = { workspace = true }
lexical-core = "0.8.5"
micromarshal = "0.5.0"
ordered-float = { workspace = true }
roaring = { version = "0.10.1", features = ["serde"] }
scroll = "0.12.0"
serde = { workspace = true }
wkt = "0.10.3"

[dev-dependencies]
aho-corasick = { version = "1.0.1" }
rand = { workspace = true }
rmp-serde = "1.1.1"

[package.metadata.cargo-machete]
ignored = ["geos"]
