[package]
authors = { workspace = true }
description = "A real-time Cloud Distributed Query Engine"
edition = { workspace = true }
license = { workspace = true }
name = "databend-enterprise-query"
publish = { workspace = true }
version = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
async-backtrace = { workspace = true }
databend-common-ast = { path = "../ast" }
databend-common-base = { path = "../../common/base" }
databend-common-catalog = { path = "../catalog" }
databend-common-config = { path = "../config" }
databend-common-exception = { path = "../../common/exception" }
databend-common-expression = { path = "../expression" }
databend-common-functions = { path = "../functions" }
databend-common-io = { path = "../../common/io" }
databend-common-license = { path = "../../common/license" }
databend-common-meta-api = { path = "../../meta/api" }
databend-common-meta-app = { path = "../../meta/app" }
databend-common-meta-store = { path = "../../meta/store" }
databend-common-meta-types = { path = "../../meta/types" }
databend-common-sql = { path = "../sql" }
databend-common-storage = { path = "../../common/storage" }
databend-common-storages-fuse = { path = "../storages/fuse" }
databend-common-storages-stream = { path = "../storages/stream" }
databend-common-tracing = { path = "../../common/tracing" }
databend-common-users = { path = "../users" }
databend-enterprise-aggregating-index = { path = "../ee_features/aggregating_index" }
databend-enterprise-background-service = { path = "../ee_features/background_service" }
databend-enterprise-data-mask-feature = { path = "../ee_features/data_mask" }
databend-enterprise-inverted-index = { path = "../ee_features/inverted_index" }
databend-enterprise-storage-encryption = { path = "../ee_features/storage_encryption" }
databend-enterprise-storage-quota = { path = "../ee_features/storage_quota" }
databend-enterprise-stream-handler = { path = "../ee_features/stream_handler" }
databend-enterprise-vacuum-handler = { path = "../ee_features/vacuum_handler" }
databend-enterprise-virtual-column = { path = "../ee_features/virtual_column" }
databend-query = { path = "../service" }
databend-storages-common-cache = { path = "../storages/common/cache" }
databend-storages-common-pruner = { path = "../storages/common/pruner" }
databend-storages-common-table-meta = { path = "../storages/common/table_meta" }
opendal = { workspace = true }

arrow-array = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
dashmap = { workspace = true }
derive-visitor = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
jwt-simple = "0.11.0"
log = { workspace = true }
tempfile = "3.4.0"

[dev-dependencies]
jsonb = { workspace = true }
tantivy = { workspace = true }

[build-dependencies]
databend-common-building = { path = "../../common/building" }
