[package]
name = "databend-common-license"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
databend-common-base = { path = "../base" }
databend-common-exception = { path = "../exception" }
jwt-simple = "0.11.0"
serde = { workspace = true }
serde_json = { workspace = true }
